"""
Live data sources:

1. NOAA NDBC realtime buoy observations - actual sensor readings (wave
   height/period/direction, wind) from the nearest offshore buoy. This is
   ground truth, not a model, but only tells you what's happening AT THE
   BUOY right now, not at the beach and not in the future.

2. Open-Meteo Marine + Weather forecast APIs - hourly wave/swell/wind
   forecasts for any lat/lon, built on NOAA's operational wave models
   (GFS-Wave / WaveWatch III) and ECMWF/GFS for wind. Free, no API key,
   several days out. This is what actually powers the forecast/scoring.

All values in this module are normalized to US units (feet, mph) before
being returned, regardless of the native unit of the upstream source:
  - Open-Meteo: requested directly in imperial (length_unit=imperial,
    wind_speed_unit=mph), since it supports that natively.
  - NDBC realtime2: always reports metric (m/s, meters) with no unit
    option, so we convert manually.
  - NOAA CO-OPS: units=english on this API returns KNOTS for wind, not
    mph (a nautical-API quirk), so we request metric and convert
    ourselves to guarantee mph.
"""
import httpx
import json
import os
from datetime import datetime, timezone

STATIONS_PATH = os.path.join(os.path.dirname(__file__), "stations.json")
with open(STATIONS_PATH) as f:
    _STATIONS = json.load(f)

HTTP_TIMEOUT = 12.0

MS_TO_MPH = 2.23694
M_TO_FT = 3.28084


def find_nearest_buoy(lat: float, lon: float, max_results: int = 1):
    """Simple flat-earth nearest-neighbor search over the NDBC station list.
    Good enough at surf-forecast scale (stations are tens/hundreds of miles
    apart); avoids pulling in a geo library for this."""
    def dist2(s):
        return (s["lat"] - lat) ** 2 + (s["lon"] - lon) ** 2

    ranked = sorted(_STATIONS, key=dist2)
    return ranked[:max_results]


def _parse_realtime2_line(station_id: str, line: str) -> dict | None:
    """Parse one row of an NDBC realtime2 text file into a normalized
    (US units) observation dict, or None if the row has no usable wave
    height. Shared by the "latest observation" and "historical" paths
    since both read the same 45-day realtime2 file/format."""
    parts = line.split()
    if len(parts) < 12:
        return None
    try:
        yr, mo, dy, hr, mn = parts[0:5]
        wdir, wspd, gst, wvht, dpd, apd, mwd = parts[5:12]

        def num(v):
            return None if v in ("MM", "999", "9999") else float(v)

        wave_height_m = num(wvht)
        if wave_height_m is None:
            return None

        wind_speed_ms = num(wspd)
        gst_ms = num(gst)
        return {
            "station_id": station_id.upper(),
            "observed_at": f"{yr}-{mo}-{dy}T{hr}:{mn}:00Z",
            "wind_dir_deg": num(wdir),
            "wind_speed_mph": round(wind_speed_ms * MS_TO_MPH, 1) if wind_speed_ms is not None else None,
            "gust_mph": round(gst_ms * MS_TO_MPH, 1) if gst_ms is not None else None,
            "wave_height_ft": round(wave_height_m * M_TO_FT, 1),
            "dominant_period_s": num(dpd),
            "avg_period_s": num(apd),
            "wave_dir_deg": num(mwd),
        }
    except ValueError:
        return None


COMPASS_TO_DEG = {
    "N": 0, "NNE": 22.5, "NE": 45, "ENE": 67.5, "E": 90, "ESE": 112.5,
    "SE": 135, "SSE": 157.5, "S": 180, "SSW": 202.5, "SW": 225,
    "WSW": 247.5, "W": 270, "WNW": 292.5, "NW": 315, "NNW": 337.5,
}


def _parse_spec_line(station_id: str, line: str) -> dict | None:
    """Parse one row of an NDBC realtime2 .spec (spectral wave summary)
    file. Unlike the plain realtime2 summary (WVHT/DPD/MWD), which is a
    single blended value across ALL wave energy hitting the buoy, the
    .spec file partitions that energy into two separate physical wave
    trains:
      - Sw* = the dominant SWELL component (longer-period energy that
        arrived from a distant wind event, decoupled from local wind).
      - WW* = the local WIND WAVE component (shorter-period chop being
        generated by the wind blowing at the buoy right now).
    Correlating swell-to-swell between an upwind buoy and a downwind one
    is a much cleaner signal than correlating blended WVHT/MWD, which can
    hide the true swell relationship under whatever local wind chop each
    buoy happens to have at that moment. Direction fields here are
    16-point compass abbreviations, not degrees, so they're converted."""
    parts = line.split()
    if len(parts) < 15:
        return None
    try:
        yr, mo, dy, hr, mn = parts[0:5]
        wvht, swh, swp, wwh, wwp, swd, wwd = parts[5:12]

        def num(v):
            return None if v in ("MM", "999", "9999") else float(v)

        def compass(v):
            return COMPASS_TO_DEG.get(v)

        return {
            "station_id": station_id.upper(),
            "observed_at": f"{yr}-{mo}-{dy}T{hr}:{mn}:00Z",
            "wave_height_ft": round(num(wvht) * M_TO_FT, 1) if num(wvht) is not None else None,
            "swell_height_ft": round(num(swh) * M_TO_FT, 1) if num(swh) is not None else None,
            "swell_period_s": num(swp),
            "swell_dir_deg": compass(swd),
            "windwave_height_ft": round(num(wwh) * M_TO_FT, 1) if num(wwh) is not None else None,
            "windwave_period_s": num(wwp),
            "windwave_dir_deg": compass(wwd),
        }
    except ValueError:
        return None


async def fetch_buoy_spectral(station_id: str) -> dict | None:
    """Pull the most recent spectral wave partition (swell vs wind-wave,
    see _parse_spec_line) for a station. Returns None if the station
    doesn't publish a .spec file or has no recent data."""
    url = f"https://www.ndbc.noaa.gov/data/realtime2/{station_id.lower()}.spec"
    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as client:
        try:
            resp = await client.get(url)
            resp.raise_for_status()
        except httpx.HTTPError:
            return None

    lines = [l for l in resp.text.splitlines() if l and not l.startswith("#")]
    for line in lines[:12]:
        obs = _parse_spec_line(station_id, line)
        if obs and obs["swell_height_ft"] is not None:
            return obs
    return None


async def fetch_buoy_observation(station_id: str) -> dict | None:
    """Pull the most recent realtime observation for a station. Returns
    None if the station has no recent data (retired buoy, outage, etc.)
    rather than raising, so the app can degrade gracefully."""
    url = f"https://www.ndbc.noaa.gov/data/realtime2/{station_id.lower()}.txt"
    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as client:
        try:
            resp = await client.get(url)
            resp.raise_for_status()
        except httpx.HTTPError:
            return None

    lines = [l for l in resp.text.splitlines() if l and not l.startswith("#")]
    if not lines:
        return None

    # Walk rows newest-first and take the first one with usable wave data,
    # since gusts/wind often report before wave sensors on a given tick.
    for line in lines[:12]:
        obs = _parse_realtime2_line(station_id, line)
        if obs:
            return obs
    return None


async def fetch_historical_observations(station_id: str) -> list[dict]:
    """Pull the full ~45-day realtime2 archive for a station (NDBC keeps a
    rolling window, no separate 'historical' endpoint needed for this
    horizon) and return every row with usable wind + wave data. This is
    the raw material for calibrating the fetch-wind model: pairing what
    the wind was actually doing with what wave height that produced at
    the SAME buoy, so a future forecast wind can be compared against real
    past analogs rather than a hand-tuned guess."""
    url = f"https://www.ndbc.noaa.gov/data/realtime2/{station_id.lower()}.txt"
    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as client:
        try:
            resp = await client.get(url)
            resp.raise_for_status()
        except httpx.HTTPError:
            return []

    lines = [l for l in resp.text.splitlines() if l and not l.startswith("#")]
    rows = []
    for line in lines:
        obs = _parse_realtime2_line(station_id, line)
        if obs and obs["wind_speed_mph"] is not None and obs["wind_dir_deg"] is not None:
            rows.append(obs)
    return rows


async def fetch_marine_forecast(lat: float, lon: float, days: int = 7) -> dict:
    """Hourly swell + wind forecast for a point, from Open-Meteo (wraps
    NOAA/ECMWF wave + atmospheric models). Requests US units directly
    from the API (feet, mph) so no manual conversion is needed here."""
    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as client:
        marine_resp, wind_resp = await client.get(
            "https://marine-api.open-meteo.com/v1/marine",
            params={
                "latitude": lat,
                "longitude": lon,
                "hourly": "wave_height,wave_direction,wave_period,"
                          "swell_wave_height,swell_wave_period,swell_wave_direction",
                "length_unit": "imperial",
                "timezone": "auto",
                "forecast_days": days,
            },
        ), await client.get(
            "https://api.open-meteo.com/v1/forecast",
            params={
                "latitude": lat,
                "longitude": lon,
                "hourly": "wind_speed_10m,wind_direction_10m,wind_gusts_10m",
                "wind_speed_unit": "mph",
                "timezone": "auto",
                "forecast_days": days,
            },
        )
        marine_resp.raise_for_status()
        wind_resp.raise_for_status()

    marine = marine_resp.json()["hourly"]
    wind = wind_resp.json()["hourly"]

    # Both endpoints return the same hourly timestamps for the same
    # lat/lon/forecast_days/timezone params, so we can zip by index safely.
    times = marine["time"]
    n = len(times)
    hours = []
    for i in range(n):
        if i >= len(wind["time"]):
            break
        hours.append({
            "time": times[i],
            "wave_height_ft": marine["wave_height"][i],
            "wave_period_s": marine["wave_period"][i],
            "wave_dir_deg": marine["wave_direction"][i],
            "swell_height_ft": marine["swell_wave_height"][i],
            "swell_period_s": marine["swell_wave_period"][i],
            "swell_dir_deg": marine["swell_wave_direction"][i],
            "wind_speed_mph": wind["wind_speed_10m"][i],
            "wind_gust_mph": wind["wind_gusts_10m"][i],
            "wind_dir_deg": wind["wind_direction_10m"][i],
        })
    return {"lat": lat, "lon": lon, "fetched_at": datetime.now(timezone.utc).isoformat(), "hours": hours}


async def find_working_nearest_buoy(lat: float, lon: float, candidates: int = 6) -> tuple[str | None, dict | None]:
    """Some NDBC stations list nearshore wave sensors but don't publish a
    realtime2 feed (retired, seasonal, or a different data product).
    Try the nearest candidates in order and return the first one with an
    actual observation, so a spot doesn't get stuck pointing at a dead
    buoy forever."""
    for station in find_nearest_buoy(lat, lon, max_results=candidates):
        obs = await fetch_buoy_observation(station["id"])
        if obs:
            return station["id"], obs
    return None, None


async def fetch_tides_currents_wind(station_id: str) -> dict | None:
    """Live wind observation from a NOAA CO-OPS (Tides & Currents) station,
    used for spots near a tide gauge but not right next to an NDBC wave
    buoy (e.g. Elwha, WA - nearest live wind is the Port Angeles tide
    station, station 9444090). Different API/format than NDBC realtime2.
    Requested in metric and converted to mph ourselves - CO-OPS's
    units=english mode actually returns knots for wind, not mph."""
    url = "https://api.tidesandcurrents.noaa.gov/api/prod/datagetter"
    params = {
        "station": station_id, "product": "wind", "units": "metric",
        "time_zone": "gmt", "format": "json", "date": "latest",
    }
    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as client:
        try:
            resp = await client.get(url, params=params)
            resp.raise_for_status()
        except httpx.HTTPError:
            return None
    try:
        data = resp.json().get("data")
        if not data:
            return None
        row = data[-1]
        speed_ms = float(row["s"]) if row.get("s") not in (None, "") else None
        gust_ms = float(row["g"]) if row.get("g") not in (None, "") else None
        return {
            "station_id": station_id,
            "observed_at": row.get("t"),
            "wind_speed_mph": round(speed_ms * MS_TO_MPH, 1) if speed_ms is not None else None,
            "wind_dir_deg": float(row["d"]) if row.get("d") not in (None, "") else None,
            "gust_mph": round(gust_ms * MS_TO_MPH, 1) if gust_ms is not None else None,
        }
    except (KeyError, ValueError, TypeError):
        return None
